############
# OpenSSL compile
############
FROM debian:11
ARG OPENSSL_VERSION=3.0.8
ARG OPENSSL_CONFIGOPTS=enable-fips
RUN apt-get update && apt-get install -y \
    make gcc wget perl
RUN mkdir -p ./build && \
    wget "https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL_VERSION/openssl-$OPENSSL_VERSION.tar.gz" -O- | \
    tar -C build --strip-components=1 -xzf -
RUN (cd build && ./Configure --prefix=/openssl $OPENSSL_CONFIGOPTS && make && make install)
